import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import { Lexend } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const merriWeather = Lexend({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${merriWeather.className} bg-gray-900`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
