export type CaseStudy = {
	id: string;
	title: string;
	description: string;
};

export const caseStudies: CaseStudy[] = [
	{
		id: "yourteacher",
		title: "YourTeacher — Agentic AI Tutor",
		description:
			"An autonomous agentic AI system for personalised learning, built with the OpenAI Agents SDK, RAG over a vector store, and a production-ready chat surface. Students can learn any topic in their own style while the agent adapts to their cognitive ability — adjusting explanation depth, examples, and pacing on the fly. The system orchestrates retrieval, tool use, and multi-step reasoning to keep responses grounded in reference material rather than hallucinating. Shipped as a Streamlit front-end backed by a Python agent loop and a managed vector database.",
	},
	{
		id: "mahaana-corporate",
		title: "Mahaana Corporate SPAs",
		description:
			"At Mahaana (YC W22) I architect the customer and corporate single-page apps that 15,000+ Pakistani savers use to onboard their pension. The stack is React, TypeScript and ASP.NET Core, with Azure Service Bus events powering the microservice backbone. I own the frontend architecture end-to-end: design-system primitives, form state, validation, KYC flows, and the integration layer that talks to onboarding, payments, and compliance services. The app has to feel instant on a 3G connection in Karachi and still satisfy regulator audits — so performance budgets and observability are first-class.",
	},
	{
		id: "automily",
		title: "Automily — GenAI QA Automation",
		description:
			"Led Automily at mParsec, a GenAI-powered QA automation platform that turns plain-English specs into executable browser tests. The system uses LLMs to plan test flows, a deterministic runner to execute them, and a self-healing layer that re-anchors selectors when the UI drifts. I owned the agent prompt design, the Playwright execution sandbox, and the reporting UI. The product cut regression-suite authoring time from days to minutes for early-access teams.",
	},
	{
		id: "dreamstream",
		title: "DreamStream — In-Flight Entertainment",
		description:
			"Shipped DreamStream, the in-flight entertainment platform now flying on PIA aircraft. The system streams movies, music, and live content to passenger devices over the cabin Wi-Fi network with zero internet egress. I built the React passenger app, the cabin-crew control panel, and the offline-first content sync pipeline. Constraints were brutal — embedded hardware, intermittent radios, and a captive audience that notices every stutter — which made it the most demanding performance work I've done.",
	},
	{
		id: "governor-sindh",
		title: "Governor Sindh IT Initiative",
		description:
			"Built the public-facing portal and admissions pipeline for the Governor Sindh IT Initiative, a province-wide programme training tens of thousands of students in software engineering. The system handles applications, cohort assignment, attendance, and certification — at peak load it served 100K+ concurrent users during result announcements. Stack: Next.js front-end, a Node.js BFF, and a Postgres backbone with aggressive caching at the edge. The interesting work was scale: turning a one-off government project into a piece of infrastructure that could survive a viral moment.",
	},
	{
		id: "dreammker",
		title: "DreamMaker — AI Storybook Generator",
		description:
			"A consumer AI tool that turns a child's prompt into a personalised illustrated storybook — text generated by an LLM, illustrations by a diffusion model, and the whole thing assembled into a printable PDF. I built the orchestration layer (prompt templates, safety filters, image-text alignment), the React editor where parents can tweak each page, and the print-fulfilment integration. The hard part was keeping characters visually consistent across pages, which we solved with reference-image conditioning and a custom prompt scaffold.",
	},
];
